### ISSUE TITLE
(*pixelgl.Window).Update() fails test

### ISSUE THREAD

**Issue by NaniteFactory** [faiface/pixel#163]
Hi,

I have a problem with `testing` and `pixelgl`.

Here is a simple test code. This one below works perfectly fine.

```Go
package main

import (
	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
)

func main() {
	pixelgl.Run(func() {
		win, err := pixelgl.NewWindow(pixelgl.WindowConfig{Bounds: pixel.R(0, 0, 1024, 768)})
		if err != nil {
			panic(err)
		}
		for !win.Closed() {
			win.Update()
		}
	})
}
```

But the exact same code as a standard unit test does not.

```Go
package main_test

import (
	"testing"

	"github.com/faiface/pixel"
	"github.com/faiface/pixel/pixelgl"
)

func TestPixelGL(t *testing.T) {
	pixelgl.Run(func() {
		win, err := pixelgl.NewWindow(pixelgl.WindowConfig{Bounds: pixel.R(0, 0, 1024, 768)})
		if err != nil {
			t.Error(err)
		}
		for !win.Closed() {
			win.Update() // (*pixelgl.Window).Update() fails test. (Others are fine.)
		}
	})
}
```

```
Running tool: D:\Go\bin\go.exe test -timeout 30s _test_pixelgl -run ^(TestPixelGL)$

Exception 0xc0000005 0x0 0xb90 0x7ff929af319e
PC=0x7ff929af319e

runtime: unknown pc 0x7ff929af319e
stack: frame={sp:0x2d2fe08, fp:0x0} stack=[0x2b31ed0,0x2d2fed0)
0000000002d2fd08:  000000c042030800  0000000002d2fd30 
0000000002d2fd18:  000000000042afb7 <runtime.stdcall1+71>  00000000006b44d0 
0000000002d2fd28:  0000000000000001  0000000002d2fd58 
0000000002d2fd38:  000000000042aabf <runtime.semawakeup+47>  00000000006b44d0 
0000000002d2fd48:  0000000000000204  0000000000000000 
0000000002d2fd58:  0000030000000400  000000000040fd60 <runtime.notewakeup+96> 
0000000002d2fd68:  000000c042042000  0000000000000000 
0000000002d2fd78:  0000000000000000  000000c0420ce078 
0000000002d2fd88:  000000c04207bed0  000000c04207bed0 
0000000002d2fd98:  000000c0420d2038  000000c04207bd78 
0000000002d2fda8:  000000c04200e044  000000c04200e048 
0000000002d2fdb8:  00000000006a0d3e  000000c000000012 
0000000002d2fdc8:  0000000002d2fde0  0000000000434bcb <runtime.schedule+283> 
0000000002d2fdd8:  000000c042046600  0000000000000000 
0000000002d2fde8:  0000030000000400  000000c04207bd78 
0000000002d2fdf8:  000000c04207bd78  000000c042026780 
0000000002d2fe08: <0000000000458cc3 <runtime.asmcgocall+115>  0000000002d2fe40 
0000000002d2fe18:  0000000000434f3b <runtime.park_m+203>  000000c0420c2180 
0000000002d2fe28:  000000c042014298  0000000000000001 
0000000002d2fe38:  0000000000000358  000000c042046600 
0000000002d2fe48:  00000000004573ce <runtime.mcall+94>  000000c0420c2180 
0000000002d2fe58:  0000000000000000  0000000000000000 
0000000002d2fe68:  0000000000000000  00000000006b20cc 
0000000002d2fe78:  0000000000000000  0000000000000000 
0000000002d2fe88:  0000000000000000  0000000000000000 
0000000002d2fe98:  0000000000000000  00000000009d6ca0 
0000000002d2fea8:  00000000006b2040  0000000000000000 
0000000002d2feb8:  00007ff9651ff0a0  0000000000000000 
0000000002d2fec8:  00007ff9651aa553 
runtime: unknown pc 0x7ff929af319e
stack: frame={sp:0x2d2fe08, fp:0x0} stack=[0x2b31ed0,0x2d2fed0)
0000000002d2fd08:  000000c042030800  0000000002d2fd30 
0000000002d2fd18:  000000000042afb7 <runtime.stdcall1+71>  00000000006b44d0 
0000000002d2fd28:  0000000000000001  0000000002d2fd58 
0000000002d2fd38:  000000000042aabf <runtime.semawakeup+47>  00000000006b44d0 
0000000002d2fd48:  0000000000000204  0000000000000000 
0000000002d2fd58:  0000030000000400  000000000040fd60 <runtime.notewakeup+96> 
0000000002d2fd68:  000000c042042000  0000000000000000 
0000000002d2fd78:  0000000000000000  000000c0420ce078 
0000000002d2fd88:  000000c04207bed0  000000c04207bed0 
0000000002d2fd98:  000000c0420d2038  000000c04207bd78 
0000000002d2fda8:  000000c04200e044  000000c04200e048 
0000000002d2fdb8:  00000000006a0d3e  000000c000000012 
0000000002d2fdc8:  0000000002d2fde0  0000000000434bcb <runtime.schedule+283> 
0000000002d2fdd8:  000000c042046600  0000000000000000 
0000000002d2fde8:  0000030000000400  000000c04207bd78 
0000000002d2fdf8:  000000c04207bd78  000000c042026780 
0000000002d2fe08: <0000000000458cc3 <runtime.asmcgocall+115>  0000000002d2fe40 
0000000002d2fe18:  0000000000434f3b <runtime.park_m+203>  000000c0420c2180 
0000000002d2fe28:  000000c042014298  0000000000000001 
0000000002d2fe38:  0000000000000358  000000c042046600 
0000000002d2fe48:  00000000004573ce <runtime.mcall+94>  000000c0420c2180 
0000000002d2fe58:  0000000000000000  0000000000000000 
0000000002d2fe68:  0000000000000000  00000000006b20cc 
0000000002d2fe78:  0000000000000000  0000000000000000 
0000000002d2fe88:  0000000000000000  0000000000000000 
0000000002d2fe98:  0000000000000000  00000000009d6ca0 
0000000002d2fea8:  00000000006b2040  0000000000000000 
0000000002d2feb8:  00007ff9651ff0a0  0000000000000000 
0000000002d2fec8:  00007ff9651aa553 

goroutine 20 [syscall]:
github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowBindFramebuffer(0x7ff929af3180, 0x100008d40)
	_cgo_gotypes.go:3015 +0x4c
github.com/go-gl/gl/v3.3-core/gl.BindFramebuffer(0x100008d40)
	D:/GoPath/src/github.com/go-gl/gl/v3.3-core/gl/package.go:8495 +0x44
github.com/faiface/glhf.NewFrame.func1(0x1)
	D:/GoPath/src/github.com/faiface/glhf/frame.go:22 +0x38
github.com/faiface/glhf.(*binder).bind(0xc0423e6000, 0x0)
	D:/GoPath/src/github.com/faiface/glhf/util.go:20 +0xbe
github.com/faiface/glhf.(*Frame).Begin(0xc0423e6000)
	D:/GoPath/src/github.com/faiface/glhf/frame.go:64 +0x34
github.com/faiface/pixel/pixelgl.(*Window).Update.func2()
	D:/GoPath/src/github.com/faiface/pixel/pixelgl/window.go:179 +0xac
github.com/faiface/mainthread.Call.func1()
	D:/GoPath/src/github.com/faiface/mainthread/mainthread.go:63 +0x39
github.com/faiface/mainthread.Run(0xc0420ca000)
	D:/GoPath/src/github.com/faiface/mainthread/mainthread.go:44 +0xc5
github.com/faiface/pixel/pixelgl.Run(0xc0420ca000)
	D:/GoPath/src/github.com/faiface/pixel/pixelgl/run.go:32 +0x60
_test_pixelgl_test.TestPixelGL(0xc0420ba0f0)
	D:/GoPath/src/_test_pixelgl/main_test.go:11 +0x63
testing.tRunner(0xc0420ba0f0, 0x5da6b8)
	D:/Go/src/testing/testing.go:777 +0xd7
created by testing.(*T).Run
	D:/Go/src/testing/testing.go:824 +0x2e7

goroutine 1 [chan receive, locked to thread]:
testing.(*T).Run(0xc0420ba0f0, 0x5ca4c6, 0xb, 0x5da6b8, 0x47365d)
	D:/Go/src/testing/testing.go:825 +0x308
testing.runTests.func1(0xc0420ba000)
	D:/Go/src/testing/testing.go:1063 +0x6b
testing.tRunner(0xc0420ba000, 0xc042073df8)
	D:/Go/src/testing/testing.go:777 +0xd7
testing.runTests(0xc042050440, 0x6c5620, 0x1, 0x1, 0x410fd3)
	D:/Go/src/testing/testing.go:1061 +0x2cb
testing.(*M).Run(0xc0420aa000, 0x0)
	D:/Go/src/testing/testing.go:978 +0x178
main.main()
	_testmain.go:44 +0x158

goroutine 34 [chan receive]:
github.com/faiface/mainthread.Call(0xc042032020)
	D:/GoPath/src/github.com/faiface/mainthread/mainthread.go:66 +0xc9
github.com/faiface/pixel/pixelgl.(*Window).Update(0xc0420dc000)
	D:/GoPath/src/github.com/faiface/pixel/pixelgl/window.go:172 +0xe8
_test_pixelgl_test.TestPixelGL.func1()
	D:/GoPath/src/_test_pixelgl/main_test.go:17 +0x14e
github.com/faiface/mainthread.Run.func1(0xc0420ca000, 0xc0420d2000)
	D:/GoPath/src/github.com/faiface/mainthread/mainthread.go:37 +0x2e
created by github.com/faiface/mainthread.Run
	D:/GoPath/src/github.com/faiface/mainthread/mainthread.go:36 +0xb9
rax     0xaec430
rbx     0xc04207bd28
rcx     0x8d40
rdi     0xc04207bd28
rsi     0xc042026780
rbp     0xc04207bcd8
rsp     0x2d2fe08
r8      0x0
r9      0x20
r10     0x10
r11     0xc04200e040
r12     0xc0420d2038
r13     0xc04207bed0
r14     0xc04207bed0
r15     0xc0420ce078
rip     0x7ff929af319e
rflags  0x10212
cs      0x33
fs      0x53
gs      0x2b
FAIL	_test_pixelgl	1.321s
Error: Tests failed.
```

`pixelgl.Run()`, `pixelgl.NewWindow()`, and `(*pixelgl.Window).Closed()` are all fine. Just `(*pixelgl.Window).Update()` seems to be the thing that causes this crash. Would there be any way we can get it pass this test?

Thanks in advance!

**Comment by faiface** [comment]
I think the problem may be that the test is not running on the main thread. `pixelgl.Run` is used to guarantee that everything that needs to runs on the main thread, but that only works if `pixelgl.Run` is itself called on the main thread. That is true if you're calling it directly from main, but probably isn't true from a test.

The main thread requirement is stupid, but it isn't my inventions, it's a requirement of some window managers and operating systems.

**Comment by NaniteFactory** [comment]
Thanks, you're right.. I looked into it again and this seems to be the same error that's raised when `pixelgl.Run` is run on a goroutine other than the main funtion. As in,

```Go
func main() {
	go pixelgl.Run(func() { ... })
}
```

Then this issue is not particularly about `(*pixelgl.Window).Update()`. It's rather regarding the requirement of `pixelgl.Run()`. GL stuff like `(*pixelgl.Window).Update()` needs to be run on mainthread and that's why we use `pixelgl.Run()`. Now I see it clearly.

So unless I can get the mainthread in the unit test I won't be able to test it with `go test`. But taking control of mainthread in a unit test - that's very unlikely. And as far as I know, for a lot of graphics frameworks, it is in practice quite common that the graphics/UI updates only on the mainthread, so the way pixel work here doesn't really seem strange. I think it was just that I was stupid. I wish I could handle mainthread execution in unit test or I hope that someday GLFW improves and gets over this system. xD

**Comment by faiface** [comment]
Yes, I'd love it if OSs didn't have this requirement, it's an especially stupid requirement. If I remember correctly, the reason is that the graphics systems are implemented with some thread-local data or something, not sure exactly.

**Comment by bcvery1** [comment]
@NaniteFactory did you find a solution to this?  I'm experiencing a very similar challenge, needed to test my library which calls `pixel`s Draw function, that is panicking due to not being called on the main thread.

Wondering if this would help: https://golang.org/pkg/testing/#hdr-Main

I'm going to see if I can get anywhere with using the `*testing.M` and I'll report back here!

**Comment by NaniteFactory** [comment]
@bcvery1 Oh that's cool. Because I wasn't aware of testing.M and until now I had to test it in a separate main package. :P
I'll also try to investigate further and get back to you soon. Thanks!

**Comment by bcvery1** [comment]
I'm succeeding using the following:
Putting my pixel specific (requiring to be run on the main thread) tests in the same place as any other test, as if no special requirements are needed.  Then putting the following at the top of my test file (note, my test file is not `package main`):
```go
func TestMain(m *testing.M) {
    pixelgl.Run(func() {
        os.Exit(m.Run())
    })
}
```

This call to `m.Run()` is running all the normal tests within `pixelgl`s `Run` on the mainthread :+1:

**Comment by NaniteFactory** [comment]
@bcvery1 

Perfect! `func TestMain(m *testing.M)` works just like `func main()` in main package. It runs on the main goroutine and from there I could create windows, update those windows, and spawn other goroutines as many as I want. With this, we can test the main function of Pixel/OpenGL. xD

An example:
```Go
package some_test

import (
	"math"
	"time"
	"testing"

	"github.com/faiface/pixel"
	"github.com/faiface/pixel/imdraw"
	"github.com/faiface/pixel/pixelgl"
	"golang.org/x/image/colornames"
)

func run() {
	cfg := pixelgl.WindowConfig{
		Title:     "Xor",
		Bounds:    pixel.R(0, 0, 1024, 768),
		Resizable: true,
		VSync:     true,
	}
	win, err := pixelgl.NewWindow(cfg)
	if err != nil {
		panic(err)
	}

	imd := imdraw.New(nil)

	canvas := pixelgl.NewCanvas(win.Bounds())

	start := time.Now()
	for !win.Closed() {
		// in case window got resized, we also need to resize our canvas
		canvas.SetBounds(win.Bounds())

		offset := math.Sin(time.Since(start).Seconds()) * 300

		// clear the canvas to be totally transparent and set the xor compose method
		canvas.Clear(pixel.Alpha(0))
		canvas.SetComposeMethod(pixel.ComposeXor)

		// red circle
		imd.Clear()
		imd.Color = pixel.RGB(1, 0, 0)
		imd.Push(win.Bounds().Center().Add(pixel.V(-offset, 0)))
		imd.Circle(200, 0)
		imd.Draw(canvas)

		// blue circle
		imd.Clear()
		imd.Color = pixel.RGB(0, 0, 1)
		imd.Push(win.Bounds().Center().Add(pixel.V(offset, 0)))
		imd.Circle(150, 0)
		imd.Draw(canvas)

		// yellow circle
		imd.Clear()
		imd.Color = pixel.RGB(1, 1, 0)
		imd.Push(win.Bounds().Center().Add(pixel.V(0, -offset)))
		imd.Circle(100, 0)
		imd.Draw(canvas)

		// magenta circle
		imd.Clear()
		imd.Color = pixel.RGB(1, 0, 1)
		imd.Push(win.Bounds().Center().Add(pixel.V(0, offset)))
		imd.Circle(50, 0)
		imd.Draw(canvas)

		win.Clear(colornames.Green)
		canvas.Draw(win, pixel.IM.Moved(win.Bounds().Center()))
		win.Update()
	}
}

func TestMain(*testing.M) {
	pixelgl.Run(run)
}
```

Result:
```
Running tool: D:\Go\bin\go.exe test -timeout 30s _test_xor_pixel -run ^(TestMain)$

ok  	_test_xor_pixel	34.233s
Success: Tests passed.
```

![xor](https://user-images.githubusercontent.com/10949969/55800940-dc4a3a80-5b0f-11e9-8375-5c7e6580f02f.PNG)

**Comment by bcvery1** [comment]
@NaniteFactory great news!

Using this technique, I have now found a data race in [faiface/glhf](https://github.com/faiface/glhf/issues/5)

**Comment by NaniteFactory** [comment]
Good thing we discovered this issue. So the test coverage went up, and we even resolved an unexpected data race with it. Special thanks to @bcvery1. `testing.M` is nice, and I guess everything is okay by now. May I close the issue. :D
