### ISSUE TITLE
Can build but can't run on Windows 10 with mingw64?

### ISSUE THREAD

**Issue by coreyog** [faiface/pixel#93]
I have a fresh install of Windows 10 x64 fully updated. I've installed mingw64 and gcc is on the path. I'm trying to build and run the code at the end of the [Moving, scaling, and rotating with Matrix tutorial](https://github.com/faiface/pixel/wiki/Moving,-scaling-and-rotating-with-Matrix). I can `go get` and `go build` without error but when I run the EXE I get:

```
panic: creating window failed: APIUnavailable: WGL: The driver does not appear to support OpenGL

goroutine 19 [running]:
main.run()
        E:/git/goprojects/src/pixelTest/main.go:31 +0x9b0
github.com/faiface/mainthread.Run.func1(0x587598, 0xc042042120)
        E:/git/goprojects/src/github.com/faiface/mainthread/mainthread.go:37 +0x2e
created by github.com/faiface/mainthread.Run
        E:/git/goprojects/src/github.com/faiface/mainthread/mainthread.go:36 +0xb9
exit status 2
```

Line 31 of main.go is the panic here:

```
        win, err := pixelgl.NewWindow(cfg)
	if err != nil {
		panic(err)
	}
```

I have a Nvidia GeForce 970 in my desktop that definitely runs OpenGL without a problem. I've installed the latest Nvidia drivers using GeForce Experience. The exact same code on my Linux Mint x64 laptop runs just fine. Something in my dependencies must be off.

Before reinstalling Windows (my old motherboard gave out, unrelated to this problem) I have run go-gl on this graphics card. I must be missing a step that I've done before but can't remember.

**Comment by coreyog** [comment]
[I opened this issue with go-gl](https://github.com/go-gl/gl/issues/91) and upon further research discovered that it was happening because I was over an RDP connection with the computer trying to run it. Apparently that confuses OpenGL initialization. Not your fault. Sorry.
